name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Déclencher le pipeline sur la branche master
  pull_request:
    branches:
      - master  # Déclencher pour les PR vers master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Version mise à jour

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Version mise à jour

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Version mise à jour
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ilyass33/myapp:latest .

      - name: Push Docker image
        run: docker push ilyass33/myapp:latest

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: build-and-test  # S'exécute après le job de build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"  # Spécifier la version

      - name: Configure Kubernetes
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG" | base64 --decode > ~/.kube/config  # Décodage base64
          kubectl cluster-info  # Vérification de la connexion

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl get pods -o wide
